# Generated by Django 4.1.1 on 2022-10-10 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='monedas',
            fields=[
                ('tasa', models.FloatField(max_length=200)),
                ('moneda', models.CharField(max_length=45)),
                ('codigomoneda', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='transaccion',
            fields=[
                ('email', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Usuario_registrado',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('direccion', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=45)),
                ('ciudad', models.CharField(max_length=45)),
                ('tipodocumento', models.CharField(max_length=45)),
                ('fechaexpedicion', models.DateField(max_length=20)),
                ('monedas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.monedas')),
            ],
        ),
    ]
