# Generated by Django 4.1.1 on 2022-10-11 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_monedas_transaccion_alter_proyecto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_registrado',
            name='monedas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.monedas'),
        ),
    ]
