# Generated by Django 4.1.1 on 2022-10-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_usuario_registrado_monedas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinatarios',
            fields=[
                ('direccion', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
