# Generated by Django 4.1.1 on 2022-10-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_destinatarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinatarios',
            name='direccion',
        ),
        migrations.AddField(
            model_name='destinatarios',
            name='tipodocumento',
            field=models.CharField(default='cc', max_length=200),
        ),
    ]
